Traceback (most recent call last):
  File "/cow02/rudenko/colowils/LLMExp/LLM-Exp/eval/evaltest.py", line 51, in <module>
    for batch, labels in dataloader:
  File "/cow02/rudenko/colowils/Miniconda3/envs/LLM/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/cow02/rudenko/colowils/Miniconda3/envs/LLM/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cow02/rudenko/colowils/Miniconda3/envs/LLM/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cow02/rudenko/colowils/Miniconda3/envs/LLM/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/cow02/rudenko/colowils/LLMExp/LLM-Exp/eval/evaltest.py", line 31, in __getitem__
    item = {key: value.squeeze() for key, value in self.tokenized_data[idx].items()}
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'